name: market_bridge
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7

  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.3.3
  flutter_local_notifications: ^17.2.2


  # Firebase dependencies (add these)
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.4

  cloud_functions: ^5.0.0

  firebase_messaging: ^15.2.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
